# Práctica Clase 3

## Numpy

In [ ]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [ ]:
array1 = np.random.rand(4,3)
array1

In [ ]:
len(array1)

In [ ]:
array1 = array1 + 0.5
array1

A partir de una lista podemos crear un arreglo de numpy

In [ ]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [ ]:
arreglo = np.arange(8)
print(arreglo)

Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [ ]:
lista + 1

In [ ]:
arreglo = arreglo + 1

In [ ]:
arreglo

2. Elevar al cuadrado todos los elementos

In [ ]:
lista**2

In [ ]:
arreglo**2

3. Sumar todos los elementos

In [ ]:
print(arreglo.sum())
print(lista.sum())

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

In [ ]:
arreglo.shape

In [53]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,"\n\n",'Shape =', arreglo.shape)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] 

 Shape = (3, 6)


In [55]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,"\n",'Shape =', arreglo.shape)

[[1 2 3 4 5 6]] 
 Shape = (1, 6)


In [58]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,"\n",'Shape =', arreglo.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
 Shape = (6, 1)


In [63]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (1,n) y (n,1)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (1,n)')  # es lo mismo que (n,)
arreglo = np.array([[1,2,3,4,5,6]]) #
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (1,n)
[[1 2 3 4 5 6]] . Shape = (1, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 



In [64]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [73]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1)
a1.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [72]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2)
a2.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [77]:
a3 = a1 * a2
a3.shape

(2, 4)

In [78]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [79]:
mat1 = np.arange(0,10,1)
print(mat1)

[0 1 2 3 4 5 6 7 8 9]


In [80]:
mat2 = np.linspace(0,9,100)
print(mat2)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [81]:
mat3 = np.arange(10,101,1)
masc = (mat3 % 3 == 0)
mat3[masc]


array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [101]:
matriz = np.zeros((5,10),dtype=int)
matriz

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [102]:
matriz[[1,3],:] = 1
matriz

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [103]:
matriz[:,[2,7]] = 2
matriz

array([[0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0]])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [104]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[138.37355975, 100.82225927, 144.78646542],
        [134.11329804, 175.55157977, 187.49110794]],

       [[157.04765551, 153.61414733, 140.65481496],
        [115.29736736, 192.54671049, 136.78415221]],

       [[188.61371201, 191.91902983, 193.50574532],
        [197.3774813 , 146.55136289, 105.87531547]],

       [[183.99160042, 124.89648144, 180.00302275],
        [136.35879085, 133.86066436, 177.55423369]]])

In [105]:
a = np.random.random((4,4))

In [106]:
a

array([[0.12313142, 0.21830871, 0.37081374, 0.17057957],
       [0.09352112, 0.56523012, 0.14399177, 0.32791651],
       [0.14118833, 0.9835822 , 0.72276773, 0.74971334],
       [0.42712107, 0.60380612, 0.80802017, 0.09143714]])

In [110]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]])
a

array([[ 10, 200,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]])

In [112]:
a.sum()-256

519

In [114]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

C:\Users\Intel\AppData\Local\Temp\ipykernel_9772\3651563978.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)


In [115]:
a

array([[ 10, -56,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int8)

In [116]:
a.sum()

519

In [117]:
a.std()

23.924904214367643

In [126]:
a.sort(axis=1)

In [119]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [120]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [121]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

In [ ]:
a.reshape(24)

In [122]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [123]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [124]:
c = a * b 
print(c) 

[[91]]


In [125]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
